# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nDys0_c0b4fPC69ubu34whE8aSabEA22
"""

from  math import pi
def Area_Rectangulo(x,y):

  return x*y

def Area_Circulo(r):
  return (pi*r*r)

a1= float(input())
b1= float(input())
a2= float(input())
b2= float(input())
r1= float(input())
r2= float(input())
Area_Total=Area_Rectangulo(a1,b1)+Area_Rectangulo(a2,b2)+Area_Circulo(r1)+Area_Circulo(r2)
print("suma total = ",Area_Total)